In [21]:
import pandas as pd
df = pd.read_csv('data.csv')
df['city_dwarka'] =1
df['num_lanes'] = 2

In [22]:
df

,edge_id,from_node_id,to_node_id,length_m,speed_limit_mps,num_lanes,priority,road_type,free_flow_travel_time_s,from_junction_degree,...,baseline_waiting_time_s,baseline_time_loss_s,baseline_speed_mps,baseline_speed_relative,baseline_departed_count,baseline_arrived_count,baseline_entered_count,baseline_left_count,is_braess_road,city_dwarka
0,423754732#0,4233121339,4233121141,107.31,13.89,2,3,highway.residential,7.725702,6,...,0,23.86,11.67,0.84,0,0,17,17,0,1
1,423754739#0,4233121338,4233121142,106.46,13.89,2,3,highway.residential,7.664507,6,...,0,14.53,11.93,0.86,0,0,11,11,0,1
2,423754745,cluster_2178265471_4233121344,4233121139,108.33,13.89,2,3,highway.residential,7.799136,8,...,1,32.46,10.23,0.74,0,0,15,15,1,1
3,423754735#0,4233121342,4233121140,107.59,13.89,2,3,highway.residential,7.745860,6,...,0,1.65,13.72,0.99,0,0,1,1,0,1
4,423754763#0,4233121345,4233121146,107.61,13.89,2,3,highway.residential,7.747300,6,...,0,53.97,11.10,0.80,0,0,30,30,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,1185440251,4233040598,cluster_4233040591_4233040593,142.21,13.89,2,3,highway.residential,10.238301,6,...,22,207.72,10.50,0.76,0,0,62,61,1,1
111,423737581,4233038882,4233038883,81.29,13.89,2,3,highway.residential,5.852412,6,...,0,15.25,12.38,0.89,0,27,27,0,1,1
112,423737595,4233038877,4233038876,56.96,13.89,2,3,highway.residential,4.100792,6,...,0,21.74,10.95,0.79,0,20,20,0,0,1
113,1185440249,4233040598,4233038877,21.78,13.89,2,3,highway.residential,1.568035,6,...,1,57.00,8.94,0.64,0,0,59,59,0,1
114,423737570#4,4233040611,4233038871,76.58,13.89,2,3,highway.residential,5.513319,6,...,29,176.17,9.59,0.69,1,0,70,71,0,1

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115 entries, 0 to 114
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   edge_id                        115 non-null    object
 1   from_node_id                   115 non-null    object
 2   to_node_id                     115 non-null    object
 3   length_m                       115 non-null    float64
 4   speed_limit_mps                115 non-null    float64
 5   num_lanes                      115 non-null    int64
 6   priority                       115 non-null    int64
 7   road_type                      115 non-null    object
 8   free_flow_travel_time_s        115 non-null    float64
 9   from_junction_degree           115 non-null    int64
 10  to_junction_degree             115 non-null    int64
 11  baseline_sampled_seconds       115 non-null    float64
 12  baseline_traveltime_s          115 non-null    float64
 13  baseline_overlap_traveltime_s  115 non-null    float64
 14  baseline_density_vpm           115 non-null    float64
 15  baseline_lane_density_vpmpl    115 non-null    float64
 16  baseline_occupancy_perc        115 non-null    float64
 17  baseline_waiting_time_s        115 non-null    int64
 18  baseline_time_loss_s           115 non-null    float64
 19  baseline_speed_mps             115 non-null    float64
 20  baseline_speed_relative        115 non-null    float64
 21  baseline_departed_count        115 non-null    int64
 22  baseline_arrived_count         115 non-null    int64
 23  baseline_entered_count         115 non-null    int64
 24  baseline_left_count            115 non-null    int64
 25  is_braess_road                 115 non-null    int64
 26  city_dwarka                    115 non-null    int64
dtypes: float64(12), int64(11), object(4)
memory usage: 24.4+ KB

In [24]:
df['road_type'].unique()

array(['highway.residential', 'highway.living_street'], dtype=object)

In [25]:
all_sumo_road_types = ['highway.residential','highway.tertiary','highway.secondary','highway.primary']

In [26]:
# performing one hot encoding on the road_types
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categories=[all_sumo_road_types], sparse_output=False, handle_unknown='ignore', dtype=int)
road_encoded = ohe.fit_transform(df[['road_type']])
encoded_df = pd.DataFrame(road_encoded, columns=ohe.get_feature_names_out(['road_type']))
df = pd.concat([df.drop('road_type', axis=1), encoded_df], axis=1)

In [27]:
df.sample(3)

,edge_id,from_node_id,to_node_id,length_m,speed_limit_mps,num_lanes,priority,free_flow_travel_time_s,from_junction_degree,to_junction_degree,...,baseline_departed_count,baseline_arrived_count,baseline_entered_count,baseline_left_count,is_braess_road,city_dwarka,road_type_highway.residential,road_type_highway.tertiary,road_type_highway.secondary,road_type_highway.primary
98,423591321#0,4231642583,4231642839,54.28,13.89,2,3,3.907847,6,6,...,0,1,6,5,0,1,1,0,0,0
13,423754715,4233121410,4233121411,55.78,13.89,2,3,4.015839,6,2,...,0,19,19,0,0,1,1,0,0,0
99,423590993,4231642582,4231642830,50.58,13.89,2,3,3.641469,6,6,...,1,0,0,1,0,1,1,0,0,0

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115 entries, 0 to 114
Data columns (total 30 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   edge_id                        115 non-null    object
 1   from_node_id                   115 non-null    object
 2   to_node_id                     115 non-null    object
 3   length_m                       115 non-null    float64
 4   speed_limit_mps                115 non-null    float64
 5   num_lanes                      115 non-null    int64
 6   priority                       115 non-null    int64
 7   free_flow_travel_time_s        115 non-null    float64
 8   from_junction_degree           115 non-null    int64
 9   to_junction_degree             115 non-null    int64
 10  baseline_sampled_seconds       115 non-null    float64
 11  baseline_traveltime_s          115 non-null    float64
 12  baseline_overlap_traveltime_s  115 non-null    float64
 13  baseline_density_vpm           115 non-null    float64
 14  baseline_lane_density_vpmpl    115 non-null    float64
 15  baseline_occupancy_perc        115 non-null    float64
 16  baseline_waiting_time_s        115 non-null    int64
 17  baseline_time_loss_s           115 non-null    float64
 18  baseline_speed_mps             115 non-null    float64
 19  baseline_speed_relative        115 non-null    float64
 20  baseline_departed_count        115 non-null    int64
 21  baseline_arrived_count         115 non-null    int64
 22  baseline_entered_count         115 non-null    int64
 23  baseline_left_count            115 non-null    int64
 24  is_braess_road                 115 non-null    int64
 25  city_dwarka                    115 non-null    int64
 26  road_type_highway.residential  115 non-null    int64
 27  road_type_highway.tertiary     115 non-null    int64
 28  road_type_highway.secondary    115 non-null    int64
 29  road_type_highway.primary      115 non-null    int64
dtypes: float64(12), int64(15), object(3)
memory usage: 27.1+ KB

In [29]:
numerical_cols = [
    'length_m', 'speed_limit_mps', 'num_lanes', 'priority',
    'free_flow_travel_time_s', 'from_junction_degree', 'to_junction_degree',
    'baseline_sampled_seconds', 'baseline_traveltime_s', 'baseline_overlap_traveltime_s',
    'baseline_density_vpm', 'baseline_lane_density_vpmpl', 'baseline_occupancy_perc',
    'baseline_waiting_time_s', 'baseline_time_loss_s', 'baseline_speed_mps',
    'baseline_speed_relative', 'baseline_departed_count', 'baseline_arrived_count',
    'baseline_entered_count', 'baseline_left_count'
]

In [30]:
#performing the feature scaling of all numerical columns using StandardScaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df.loc[:,numerical_cols] = scaler.fit_transform(df[numerical_cols])

/tmp/ipykernel_7773/2106137439.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.23461857  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857
  0.23461857 -4.26223728  0.23461857 -4.26223728  0.23461857  0.23461857
  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857
  0.23461857  0.23461857 -4.26223728  0.23461857 -4.26223728  0.23461857
  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857
  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857
 -4.26223728  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857
  0.23461857  0.23461857  0.23461857 -4.26223728  0.23461857  0.23461857
  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857
  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857
  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857
  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857
  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857
  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857
  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857
  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857
  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857
  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857
  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857  0.23461857
  0.23461857]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:,numerical_cols] = scaler.fit_transform(df[numerical_cols])
/tmp/ipykernel_7773/2106137439.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.62173517 -0.62173517  0.93260276 -0.62173517 -0.62173517  0.93260276
 -0.62173517 -0.62173517  0.93260276  0.93260276 -0.62173517  0.93260276
  0.93260276 -0.62173517 -3.73041102 -0.62173517  0.93260276  0.93260276
  0.93260276  0.93260276  0.93260276  0.93260276  0.93260276  0.93260276
  0.93260276 -3.73041102 -0.62173517  0.93260276  0.93260276  0.93260276
 -0.62173517 -0.62173517 -0.62173517 -0.62173517 -0.62173517  0.93260276
 -2.1760731   0.93260276  0.93260276  0.93260276  0.93260276  0.93260276
  0.93260276  0.93260276 -0.62173517 -0.62173517 -0.62173517 -0.62173517
 -0.62173517 -0.62173517 -0.62173517 -0.62173517 -0.62173517 -0.62173517
 -0.62173517 -0.62173517  0.93260276  0.93260276  0.93260276  0.93260276
  0.93260276  0.93260276  0.93260276  0.93260276 -0.62173517 -0.62173517
  0.93260276 -0.62173517  0.93260276 -0.62173517  0.93260276  0.93260276
 -0.62173517  0.93260276  0.93260276  0.93260276 -3.73041102  0.93260276
 -0.62173517  0.93260276  0.93260276  0.93260276 -0.62173517 -0.62173517
  0.93260276  0.93260276  0.93260276 -0.62173517 -0.62173517 -0.62173517
  0.93260276 -0.62173517 -0.62173517  0.93260276 -0.62173517 -0.62173517
 -0.62173517 -0.62173517 -0.62173517 -0.62173517 -0.62173517 -0.62173517
  0.93260276 -0.62173517  0.93260276  0.93260276 -0.62173517 -0.62173517
 -0.62173517 -0.62173517 -0.62173517 -0.62173517 -0.62173517 -0.62173517
 -0.62173517]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:,numerical_cols] = scaler.fit_transform(df[numerical_cols])
/tmp/ipykernel_7773/2106137439.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.77942251 -0.4318422  -0.4318422   0.77942251  0.77942251 -0.4318422
  0.77942251  0.77942251  0.77942251  0.77942251 -2.85437162 -2.85437162
 -2.85437162 -2.85437162 -0.4318422  -2.85437162 -0.4318422  -0.4318422
  0.77942251 -0.4318422  -1.64310691 -0.4318422  -1.64310691  0.77942251
 -2.85437162  0.77942251  0.77942251 -0.4318422   0.77942251 -0.4318422
 -0.4318422  -0.4318422   0.77942251 -0.4318422  -0.4318422  -0.4318422
  0.77942251  0.77942251 -0.4318422  -0.4318422   0.77942251 -0.4318422
 -0.4318422  -0.4318422  -0.4318422  -0.4318422  -0.4318422   0.77942251
  0.77942251  0.77942251  0.77942251  0.77942251  0.77942251  0.77942251
  0.77942251  0.77942251  0.77942251  0.77942251  0.77942251  0.77942251
  0.77942251  0.77942251  0.77942251 -0.4318422  -0.4318422   0.77942251
 -0.4318422  -0.4318422   0.77942251  0.77942251  0.77942251  0.77942251
  0.77942251  0.77942251  0.77942251  0.77942251  0.77942251  0.77942251
 -0.4318422  -0.4318422  -0.4318422  -0.4318422   0.77942251  0.77942251
  0.77942251  0.77942251 -0.4318422  -0.4318422   0.77942251  0.77942251
 -0.4318422   0.77942251  0.77942251 -0.4318422  -0.4318422  -0.4318422
 -0.4318422  -0.4318422  -0.4318422  -0.4318422   0.77942251 -0.4318422
 -0.4318422   0.77942251 -0.4318422  -0.4318422   0.77942251  0.77942251
  0.77942251  0.77942251  0.77942251 -2.85437162 -2.85437162 -0.4318422
  0.77942251]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:,numerical_cols] = scaler.fit_transform(df[numerical_cols])
/tmp/ipykernel_7773/2106137439.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-3.34695012e-01 -3.34695012e-01 -3.33629488e-01 -3.34695012e-01
 -3.34695012e-01  4.05206763e+00 -3.34695012e-01 -3.34695012e-01
 -3.34695012e-01 -3.34695012e-01 -3.34695012e-01 -3.34695012e-01
 -3.34695012e-01 -3.34695012e-01 -3.34695012e-01 -3.34695012e-01
 -3.34695012e-01 -3.34695012e-01 -3.34695012e-01 -3.34695012e-01
 -3.34695012e-01 -3.34695012e-01 -3.34695012e-01 -3.34695012e-01
 -3.34695012e-01 -3.30432915e-01 -3.34695012e-01 -3.34695012e-01
 -3.34695012e-01 -3.34695012e-01 -3.34695012e-01 -3.34695012e-01
 -3.34695012e-01 -3.34695012e-01 -3.34695012e-01 -3.34695012e-01
 -3.34695012e-01 -3.34695012e-01 -3.34695012e-01 -3.34695012e-01
 -3.34695012e-01 -3.34695012e-01 -3.34695012e-01  5.96042125e+00
  5.29446870e+00 -3.34695012e-01 -1.39704105e-01 -3.20843199e-01
 -3.34695012e-01 -3.34695012e-01 -3.34695012e-01 -3.34695012e-01
 -3.34695012e-01 -3.34695012e-01 -3.34695012e-01 -2.88877476e-01
 -3.33629488e-01  5.20902294e-02  2.93964196e-01  9.55654649e-01
  1.59390357e+00  3.07612169e-03  2.85015646e+00  4.96413771e-01
  8.70412723e-01 -1.42900677e-01 -3.27236343e-01  2.27901703e-01
  4.30351278e-01  1.77184609e+00 -3.25105295e-01 -3.12319006e-01
 -2.28142604e-01 -2.97401669e-01 -3.22974247e-01 -2.75025663e-01
  1.55446065e-01 -3.18712150e-01 -3.34695012e-01 -3.18712150e-01
 -3.29367391e-01 -3.34695012e-01 -3.34695012e-01 -3.34695012e-01
 -3.34695012e-01 -3.34695012e-01 -3.34695012e-01 -4.16758897e-02
  4.65513572e-01 -2.84615380e-01 -1.65276683e-01 -3.34695012e-01
 -3.34695012e-01 -3.34695012e-01 -3.34695012e-01  4.14164577e-03
 -2.96336145e-01  6.55176859e-01 -3.34695012e-01 -3.34695012e-01
 -3.34695012e-01 -3.34695012e-01  1.65783502e+00 -3.34695012e-01
  2.39517768e+00 -3.34695012e-01 -2.67566995e-01 -3.34695012e-01
 -3.34695012e-01 -1.42900677e-01 -3.11253482e-01 -3.34695012e-01
 -3.34695012e-01 -3.33629488e-01 -3.03794813e-01]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:,numerical_cols] = scaler.fit_transform(df[numerical_cols])
/tmp/ipykernel_7773/2106137439.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.19989697 -0.19989697 -0.19989697 -0.19989697 -0.19989697 -0.19989697
 -0.19989697 -0.19989697 -0.19989697 -0.19989697 -0.19989697 -0.19989697
 -0.19989697 -0.19989697  6.5432941  -0.19989697 -0.19989697 -0.19989697
 -0.19989697 -0.19989697 -0.19989697 -0.19989697 -0.19989697 -0.19989697
 -0.19989697  6.5432941  -0.19989697 -0.19989697  0.10661172 -0.19989697
 -0.19989697 -0.19989697 -0.19989697 -0.19989697 -0.19989697 -0.19989697
 -0.19989697 -0.19989697 -0.19989697 -0.19989697 -0.19989697 -0.19989697
 -0.19989697 -0.19989697 -0.19989697 -0.19989697 -0.19989697 -0.19989697
 -0.19989697 -0.19989697 -0.19989697  0.10661172 -0.19989697 -0.19989697
 -0.19989697  0.10661172 -0.19989697 -0.19989697 -0.19989697 -0.19989697
 -0.19989697  0.10661172  0.10661172  0.10661172  0.4131204  -0.19989697
 -0.19989697 -0.19989697 -0.19989697 -0.19989697 -0.19989697 -0.19989697
 -0.19989697 -0.19989697 -0.19989697 -0.19989697  5.01075068 -0.19989697
 -0.19989697 -0.19989697 -0.19989697 -0.19989697 -0.19989697 -0.19989697
 -0.19989697 -0.19989697  0.10661172 -0.19989697 -0.19989697 -0.19989697
  0.10661172 -0.19989697 -0.19989697 -0.19989697 -0.19989697 -0.19989697
  0.10661172 -0.19989697 -0.19989697  0.10661172 -0.19989697 -0.19989697
 -0.19989697  0.10661172 -0.19989697 -0.19989697 -0.19989697 -0.19989697
 -0.19989697 -0.19989697 -0.19989697 -0.19989697 -0.19989697 -0.19989697
  0.10661172]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:,numerical_cols] = scaler.fit_transform(df[numerical_cols])
/tmp/ipykernel_7773/2106137439.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.27049887 -0.27049887 -0.27049887 -0.27049887 -0.27049887 -0.27049887
 -0.27049887 -0.27049887 -0.27049887 -0.27049887  6.64225005  3.18587559
  3.02876766  2.7145518  -0.27049887  1.92901215 -0.11339094 -0.27049887
 -0.27049887 -0.27049887 -0.27049887 -0.11339094 -0.27049887 -0.27049887
  3.02876766 -0.27049887 -0.27049887 -0.27049887  0.04371699 -0.27049887
 -0.27049887 -0.27049887 -0.27049887 -0.27049887 -0.27049887 -0.27049887
 -0.27049887 -0.27049887 -0.27049887 -0.27049887 -0.27049887 -0.27049887
 -0.11339094 -0.27049887 -0.27049887 -0.27049887 -0.27049887 -0.27049887
 -0.27049887 -0.27049887 -0.27049887 -0.27049887 -0.27049887 -0.27049887
 -0.27049887 -0.27049887 -0.27049887 -0.27049887 -0.27049887 -0.27049887
 -0.27049887 -0.27049887 -0.27049887 -0.27049887 -0.27049887 -0.27049887
 -0.27049887 -0.27049887 -0.27049887 -0.27049887 -0.27049887 -0.11339094
 -0.27049887 -0.27049887 -0.27049887 -0.27049887 -0.27049887 -0.27049887
 -0.27049887 -0.27049887 -0.27049887 -0.27049887 -0.11339094 -0.27049887
 -0.27049887 -0.27049887 -0.27049887 -0.27049887 -0.27049887 -0.27049887
 -0.27049887 -0.27049887 -0.27049887 -0.27049887 -0.27049887 -0.27049887
 -0.27049887 -0.27049887 -0.11339094 -0.27049887 -0.27049887 -0.27049887
 -0.11339094 -0.27049887 -0.27049887 -0.11339094 -0.27049887 -0.27049887
 -0.27049887 -0.27049887 -0.27049887  3.97141524  2.87165973 -0.27049887
 -0.27049887]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:,numerical_cols] = scaler.fit_transform(df[numerical_cols])
/tmp/ipykernel_7773/2106137439.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.26519201e-01 -5.06972522e-01 -4.53336975e-01 -6.41061391e-01
 -2.52203672e-01  3.24378463e-01 -3.86292541e-01 -6.54470278e-01
 -2.38794785e-01 -6.54470278e-01 -6.44792560e-02 -3.59474767e-01
 -3.72883654e-01 -3.99701428e-01 -6.54470278e-01 -4.66745862e-01
 -3.99701428e-01 -6.41061391e-01 -4.39928088e-01 -3.72883654e-01
 -6.54470278e-01  1.36654047e-01 -6.54470278e-01 -6.54470278e-01
 -3.72883654e-01 -6.54470278e-01  4.98693992e-01 -6.41061391e-01
  2.03698481e-01 -6.54470278e-01 -6.41061391e-01 -6.41061391e-01
 -6.54470278e-01 -6.54470278e-01 -6.14243617e-01 -6.54470278e-01
 -6.54470278e-01 -3.99701428e-01 -1.18114803e-01 -3.72883654e-01
 -4.39928088e-01 -6.41061391e-01 -3.99701428e-01  2.93829521e-02
 -1.18114803e-01 -6.54470278e-01 -5.60608070e-01 -6.41061391e-01
 -6.41061391e-01 -6.54470278e-01 -6.54470278e-01 -6.54470278e-01
 -6.54470278e-01 -6.41061391e-01 -6.54470278e-01  1.22277388e+00
  2.17107368e-01  1.09836273e-01 -2.65612559e-01 -2.79021446e-01
 -2.92430333e-01 -1.44932577e-01 -1.18114803e-01  2.93829521e-02
  3.78014011e-01  1.77253824e+00  4.88340000e+00  5.64770655e+00
  3.01956472e+00  2.57334029e-01  9.14369485e-01  7.26645069e-01
 -3.05839220e-01  1.09836273e-01  9.94822806e-01  1.54458717e+00
 -6.54470278e-01  1.31663609e+00 -2.52203672e-01  7.80280616e-01
  1.75912936e+00  2.56517836e-03  1.59740652e-02 -6.14243617e-01
 -5.87425844e-01 -4.93563636e-01 -4.13110314e-01 -3.99701428e-01
 -3.99701428e-01  1.31663609e+00  1.27640943e+00 -5.20381409e-01
 -6.54470278e-01  1.19595611e+00  1.19595611e+00  1.18254722e+00
  1.18254722e+00  1.22277388e+00 -5.74016957e-01 -6.54470278e-01
 -6.00834731e-01 -6.54470278e-01 -4.39928088e-01 -6.54470278e-01
 -3.72883654e-01 -1.08437085e-02  1.75912936e+00 -1.18114803e-01
 -5.87425844e-01  2.56517836e-03  1.76880708e-01 -2.92430333e-01
 -3.86292541e-01  1.36654047e-01  2.84151802e-01]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:,numerical_cols] = scaler.fit_transform(df[numerical_cols])
/tmp/ipykernel_7773/2106137439.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-4.07673488e-01 -4.87609466e-01 -4.34318814e-01 -6.20836096e-01
 -2.34478869e-01  3.11750314e-01 -3.67705499e-01 -6.34158759e-01
 -2.21156206e-01 -6.34158759e-01 -6.34158759e-01 -6.34158759e-01
 -6.34158759e-01 -6.34158759e-01 -3.41060173e-01 -6.34158759e-01
 -3.94350825e-01 -6.20836096e-01 -4.20996151e-01 -3.54382836e-01
 -6.34158759e-01  1.38555695e-01 -6.34158759e-01 -6.34158759e-01
 -6.34158759e-01 -3.41060173e-01  5.11590259e-01 -6.20836096e-01
  2.05169010e-01 -6.34158759e-01 -6.20836096e-01 -6.20836096e-01
 -6.34158759e-01 -6.34158759e-01 -5.94190770e-01 -6.34158759e-01
 -6.34158759e-01 -3.94350825e-01 -1.01252239e-01 -3.54382836e-01
 -4.20996151e-01 -6.20836096e-01 -3.94350825e-01  4.52970542e-02
 -1.27897565e-01 -6.34158759e-01 -5.40900118e-01 -6.20836096e-01
 -6.20836096e-01 -6.34158759e-01 -6.34158759e-01 -6.20836096e-01
 -6.34158759e-01 -6.20836096e-01 -6.34158759e-01  1.23101406e+00
  2.31814336e-01  1.11910369e-01 -2.61124195e-01 -2.74446858e-01
 -2.87769521e-01 -1.14574902e-01 -1.01252239e-01  5.86197172e-02
  4.18331618e-01  1.77724324e+00  4.86810106e+00  5.62749285e+00
  3.00292824e+00  2.71782325e-01  9.24592812e-01  7.11430204e-01
 -2.87769521e-01  1.11910369e-01  1.00452879e+00  1.55075797e+00
 -4.07673488e-01  1.32427270e+00 -2.34478869e-01  7.91366182e-01
  1.76392058e+00  1.86517282e-02  1.86517282e-02 -5.94190770e-01
 -5.67545444e-01 -4.74286803e-01 -3.81028162e-01 -3.81028162e-01
 -3.81028162e-01  1.32427270e+00  1.29762738e+00 -5.00932129e-01
 -6.34158759e-01  1.20436874e+00  1.20436874e+00  1.19104607e+00
  1.20436874e+00  1.23101406e+00 -5.67545444e-01 -6.20836096e-01
 -5.80868107e-01 -6.34158759e-01 -4.34318814e-01 -6.20836096e-01
 -3.54382836e-01 -7.99359780e-03  1.76392058e+00 -1.01252239e-01
 -5.67545444e-01  5.32906520e-03  1.78523684e-01 -6.34158759e-01
 -6.34158759e-01  1.51878358e-01  3.11750314e-01]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[:,numerical_cols] = scaler.fit_transform(df[numerical_cols])

In [31]:
df

,edge_id,from_node_id,to_node_id,length_m,speed_limit_mps,num_lanes,priority,free_flow_travel_time_s,from_junction_degree,to_junction_degree,...,baseline_departed_count,baseline_arrived_count,baseline_entered_count,baseline_left_count,is_braess_road,city_dwarka,road_type_highway.residential,road_type_highway.tertiary,road_type_highway.secondary,road_type_highway.primary
0,423754732#0,4233121339,4233121141,1.064321,0.318047,0,0.234619,0.379660,-0.621735,0.779423,...,-0.199897,-0.270499,-0.426519,-0.407673,0,1,1,0,0,0
1,423754739#0,4233121338,4233121142,1.045773,0.318047,0,0.234619,0.370315,-0.621735,-0.431842,...,-0.199897,-0.270499,-0.506973,-0.487609,0,1,1,0,0,0
2,423754745,cluster_2178265471_4233121344,4233121139,1.086579,0.318047,0,0.234619,0.390873,0.932603,-0.431842,...,-0.199897,-0.270499,-0.453337,-0.434319,1,1,1,0,0,0
3,423754735#0,4233121342,4233121140,1.070431,0.318047,0,0.234619,0.382738,-0.621735,0.779423,...,-0.199897,-0.270499,-0.641061,-0.620836,0,1,1,0,0,0
4,423754763#0,4233121345,4233121146,1.070868,0.318047,0,0.234619,0.382958,-0.621735,0.779423,...,-0.199897,-0.270499,-0.252204,-0.234479,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,1185440251,4233040598,cluster_4233040591_4233040593,1.825906,0.318047,0,0.234619,0.763326,-0.621735,0.779423,...,-0.199897,-0.270499,0.176881,0.178524,1,1,1,0,0,0
111,423737581,4233038882,4233038883,0.496515,0.318047,0,0.234619,0.093613,-0.621735,-2.854372,...,-0.199897,3.971415,-0.292430,-0.634159,1,1,1,0,0,0
112,423737595,4233038877,4233038876,-0.034412,0.318047,0,0.234619,-0.173854,-0.621735,-2.854372,...,-0.199897,2.871660,-0.386293,-0.634159,0,1,1,0,0,0
113,1185440249,4233040598,4233038877,-0.802107,0.318047,0,0.234619,-0.560599,-0.621735,-0.431842,...,-0.199897,-0.270499,0.136654,0.151878,0,1,1,0,0,0
114,423737570#4,4233040611,4233038871,0.393734,0.318047,0,0.234619,0.041835,-0.621735,0.779423,...,0.106612,-0.270499,0.284152,0.311750,0,1,1,0,0,0

In [32]:
from sklearn.model_selection import train_test_split
x = df.drop(['edge_id', 'from_node_id', 'to_node_id', 'is_braess_road'], axis=1)
y = df['is_braess_road']
x_train , x_test  ,y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [33]:
x_train

,length_m,speed_limit_mps,num_lanes,priority,free_flow_travel_time_s,from_junction_degree,to_junction_degree,baseline_sampled_seconds,baseline_traveltime_s,baseline_overlap_traveltime_s,...,baseline_speed_relative,baseline_departed_count,baseline_arrived_count,baseline_entered_count,baseline_left_count,city_dwarka,road_type_highway.residential,road_type_highway.tertiary,road_type_highway.secondary,road_type_highway.primary
31,-0.300640,0.318047,0,0.234619,-0.307973,-0.621735,-0.431842,-0.484704,-0.284270,-0.276170,...,0.138092,-0.199897,-0.270499,-0.641061,-0.620836,1,1,0,0,0
67,-0.553774,0.318047,0,0.234619,-0.435495,-0.621735,-0.431842,1.488148,-0.354291,-0.346052,...,0.284593,-0.199897,-0.270499,5.647707,5.627493,1,1,0,0,0
93,-1.187046,0.318047,0,0.234619,-0.754521,0.932603,-0.431842,-0.396337,-0.485580,-0.486914,...,1.104995,-0.199897,-0.270499,1.195956,1.204369,1,1,0,0,0
109,0.347035,0.318047,0,0.234619,0.018309,-0.621735,0.779423,0.067356,-0.055560,-0.053351,...,-0.154908,-0.199897,-0.270499,0.002565,0.005329,1,1,0,0,0
22,-0.439209,-3.219728,0,-4.262237,0.254840,0.932603,-1.643107,-0.490665,-0.498518,-0.514355,...,-1.473411,-0.199897,-0.270499,-0.654470,-0.634159,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,-1.053932,0.318047,0,0.234619,-0.687462,-0.621735,0.779423,-0.183963,-0.447906,-0.446302,...,0.255293,-0.199897,-0.270499,1.759129,1.763921,1,1,0,0,0
14,-0.726167,0.318047,0,0.234619,-0.522342,-3.730411,-0.431842,-0.435859,-0.404523,-0.394713,...,0.489693,6.543294,-0.270499,-0.654470,-0.341060,1,1,0,0,0
92,-0.044014,0.318047,0,0.234619,-0.178691,-0.621735,0.779423,-0.490665,-0.498518,-0.514355,...,-1.473411,-0.199897,-0.270499,-0.654470,-0.634159,1,1,0,0,0
51,1.164484,0.318047,0,0.234619,0.430119,-0.621735,0.779423,-0.479850,-0.058604,-0.062864,...,0.518993,0.106612,-0.270499,-0.654470,-0.620836,1,1,0,0,0
102,-0.395783,0.318047,0,0.234619,-0.355904,0.932603,-0.431842,1.360689,4.264045,4.108853,...,-1.385511,-0.199897,-0.113391,-0.439928,-0.434319,1,1,0,0,0

In [36]:
# Training the Model
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 100,random_state = 42)
rf.fit(x_train,y_train)
y_pred = rf.predict(x_test)
y_pred_proba = rf.predict_proba(x_test)[:, 1] # Probabilities for the positive class

In [37]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision: {precision_score(y_test, y_pred):.4f}")
print(f"Recall: {recall_score(y_test, y_pred):.4f}")
print(f"F1-Score: {f1_score(y_test, y_pred):.4f}")
print(f"ROC AUC Score: {roc_auc_score(y_test, y_pred_proba):.4f}")

Accuracy: 0.6522
Precision: 0.6250
Recall: 0.5000
F1-Score: 0.5556
ROC AUC Score: 0.6692